[build]
watchPatterns = ["/packages/kharkiv-metro-bot/**", "/packages/kharkiv-metro-core/**"]
buildCommand = "uv pip install -e ./packages/kharkiv-metro-bot -e ./packages/kharkiv-metro-cli"

[deploy]
preDeployCommand = ["metro init && metro scrape"]
startCommand = "metro-bot"

[env]
DB_PATH = "/db/metro.db"
ENABLE_USER_DATA = true
USER_DATA_DB_PATH = "/db/user_data.db"
